# API Configuration
api:
  host: "0.0.0.0"
  port: 8000
  debug: false
  reload: false
  workers: 4
  
  # CORS settings
  cors:
    allow_origins: ["*"]
    allow_credentials: true
    allow_methods: ["GET", "POST", "PUT", "DELETE"]
    allow_headers: ["*"]
    
  # Rate limiting
  rate_limiting:
    enabled: true
    requests_per_minute: 60
    burst_size: 10
    
  # Authentication
  auth:
    enabled: false
    jwt_secret: "${JWT_SECRET}"
    jwt_algorithm: "HS256"
    jwt_expiry_hours: 24
    
  # API versioning
  versioning:
    default_version: "v1"
    supported_versions: ["v1"]

# Chat Configuration
chat:
  # Conversation settings
  conversation:
    max_history_length: 10
    enable_memory: true
    memory_window: 5
    
  # Response generation
  response:
    max_response_length: 2048
    include_sources: true
    include_confidence_score: true
    stream_response: true
    
  # Safety and filtering
  safety:
    enable_content_filter: true
    enable_pii_detection: true
    enable_toxicity_filter: true
    max_query_length: 1000
    
  # Personalization
  personalization:
    enable_user_profiles: false
    adapt_to_user_style: false
    remember_preferences: false

# Monitoring and Logging
monitoring:
  # Logging configuration
  logging:
    level: "INFO"
    format: "json"
    log_file: "logs/app.log"
    max_size_mb: 100
    backup_count: 5
    
  # Metrics collection
  metrics:
    enabled: true
    provider: "prometheus"  # prometheus, datadog, custom
    port: 9090
    
    # Key metrics to track
    track_metrics:
      - "request_count"
      - "response_time"
      - "retrieval_accuracy"
      - "user_satisfaction"
      - "error_rate"
      
  # Health checks
  health_checks:
    enabled: true
    endpoint: "/health"
    check_database: true
    check_vector_store: true
    check_llm: true
    
  # Alerting
  alerting:
    enabled: false
    slack_webhook: "${SLACK_WEBHOOK_URL}"
    email_recipients: []
    error_threshold: 10
    response_time_threshold: 5000  # ms

# Environment Configuration
environment:
  name: "development"  # development, staging, production
  debug: true
  testing: false
  
# Feature Flags
features:
  experimental_retrieval: false
  advanced_reranking: true
  semantic_search: true
  query_expansion: true
  conversation_memory: true
