# Data Ingestion Configuration
ingestion:
  # Supported file formats and processors
  processors:
    pdf:
      library: "pymupdf"  # pymupdf, pdfplumber, pypdf
      extract_images: true
      extract_tables: true
      ocr_enabled: true
      
    docx:
      extract_images: false
      extract_tables: true
      
    html:
      remove_navigation: true
      remove_ads: true
      extract_main_content: true
      
    csv:
      encoding: "utf-8"
      delimiter: ","
      
    txt:
      encoding: "utf-8"
      
    json:
      flatten_nested: true
      max_depth: 5

  # Text processing pipeline
  text_processing:
    # Cleaning
    cleaning:
      remove_extra_whitespace: true
      remove_special_chars: false
      normalize_unicode: true
      remove_urls: false
      remove_emails: false
      
    # Language detection and processing
    language:
      detect_language: true
      default_language: "en"
      supported_languages: ["en", "vi", "fr", "es", "de"]
      
    # Text splitting strategy
    splitting:
      strategy: "recursive"  # recursive, semantic, sentence, token
      chunk_size: 1000
      chunk_overlap: 200
      separators: ["\n\n", "\n", " ", ""]
      
      # Semantic splitting (experimental)
      semantic:
        model: "sentence-transformers/all-MiniLM-L6-v2"
        similarity_threshold: 0.8
        
      # Token-based splitting
      token:
        model: "gpt2"
        max_tokens: 512

  # Web crawling configuration
  web_crawling:
    max_depth: 3
    max_pages: 100
    respect_robots_txt: true
    delay_between_requests: 1.0
    user_agent: "RAG-Chatbot/1.0"
    
    # Content extraction
    content_selectors:
      main_content: ["main", "article", ".content", "#content"]
      exclude_selectors: [".nav", ".sidebar", ".ads", ".footer"]
      
  # Batch processing
  batch_processing:
    batch_size: 50
    max_workers: 4
    enable_progress_bar: true
    
  # Error handling
  error_handling:
    skip_failed_files: true
    log_errors: true
    max_retries: 3
    
  # Deduplication
  deduplication:
    enabled: true
    similarity_threshold: 0.95
    method: "hash"  # hash, semantic
