# Retrieval Configuration
retrieval:
  # Basic retrieval settings
  top_k: 10
  similarity_threshold: 0.7
  max_context_length: 4000
  
  # Advanced retrieval strategies
  strategy: "hybrid"  # simple, hybrid, multi_query, contextual_compression
  
  # Reranking configuration
  reranking:
    enabled: true
    model: "cross-encoder/ms-marco-MiniLM-L-12-v2"
    top_k_rerank: 5
    
  # Multi-query retrieval
  multi_query:
    enabled: true
    num_queries: 3
    diversity_penalty: 0.5
    
  # Contextual compression
  contextual_compression:
    enabled: true
    compression_model: "gpt-3.5-turbo"
    max_compression_ratio: 0.5
    
  # Hybrid search (semantic + keyword)
  hybrid_search:
    enabled: true
    semantic_weight: 0.7
    keyword_weight: 0.3
    keyword_index: "bm25"
    
  # Document filtering
  filtering:
    enable_metadata_filtering: true
    enable_content_filtering: true
    allowed_file_types: ["pdf", "txt", "docx", "html", "md"]
    max_document_age_days: 365
    
  # Advanced features
  features:
    enable_query_expansion: true
    enable_spell_correction: true
    enable_synonym_expansion: true
    enable_temporal_filtering: false

# Query Processing
query_processing:
  # Query preprocessing
  preprocessing:
    remove_stopwords: false
    normalize_text: true
    expand_abbreviations: true
    correct_spelling: true
    
  # Query analysis
  analysis:
    detect_intent: true
    extract_entities: true
    classify_domain: true
    
  # Query transformation
  transformation:
    enable_query_rewriting: true
    enable_query_decomposition: true
    max_sub_queries: 3
